### ISSUE TITLE
进入聊天页面很慢，而且autolayout报错。

### ISSUE THREAD

**Issue by ZsIsMe** [weida-studio/QQ#2]
出错的地方很多，部分：
Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2015-12-15 14:54:34.194 QQ[2675:137483] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7faaf5111cc0 H:|-(10)-[UIImageView:0x7faaf2c537e0]   (Names: '|':UITableViewCellContentView:0x7faaf2c53130 )>",
    "<NSLayoutConstraint:0x7faaf5113350 H:[UIImageView:0x7faaf2c537e0]-(0)-[UIImageView:0x7faaf5111e60]>",
    "<NSLayoutConstraint:0x7faaf5031ec0 UILabel:0x7faaf5113a00'50'        '.trailing == UIImageView:0x7faaf5111e60.trailing - 20>",
    "<NSLayoutConstraint:0x7faaf50320b0 UILabel:0x7faaf5113a00'50'        '.trailing <= UITableViewCellContentView:0x7faaf2c53130.trailing - 40>",
    "<NSLayoutConstraint:0x7faaf52dcbf0 H:[UITableViewCellContentView:0x7faaf2c53130(0)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7faaf5113350 H:[UIImageView:0x7faaf2c537e0]-(0)-[UIImageView:0x7faaf5111e60]>

**Comment by weida-studio** [comment]
进入聊天界面慢的原因是，首次进入界面，显示的聊天消息过于多了，我直接显示200条，当然是为了测试性能。一般像QQ第一次进入界面，只会显示10-20条最近消息，这样就不会卡。当然界面性能还是需要优化。至于你说的是警告，其实是因为我把TableView 也用自动布局进行布局的，显示警告很多，其实只是一个问题，待修改一下，这个我确定不是大问题。

**Comment by weida-studio** [comment]
你好，警告问题，已经修复了，现在什么警告、错误都没有了

**Comment by weida-studio** [comment]
你好，警告这个问题已经修复了，。。多谢你的反馈。。

发自我的 iPhone
